export interface TermDefinition {
  term: string;
  description: string;
}

export const coreTerms: TermDefinition[] = [
  {
    term: 'OSI Model',
    description: 'A conceptual framework used to understand network interactions in seven layers: Physical, Data Link, Network, Transport, Session, Presentation, Application.',
  },
  {
    term: 'TCP/IP Model',
    description: 'A four-layer communication model (Network Interface, Internet, Transport, Application) used for data transmission over a network.',
  },
  {
    term: 'IP Address',
    description: 'A unique identifier for a device on a network, used for locating and differentiating devices.',
  },
  {
    term: 'MAC Address',
    description: 'A hardware identification number that uniquely identifies each device on a network.',
  },
  {
    term: 'Subnet Mask',
    description: 'A 32-bit number used to divide IP address into network and host address.',
  },
  {
    term: 'DHCP',
    description: 'Dynamic Host Configuration Protocol assigns IP addresses dynamically to devices on a network.',
  },
  {
    term: 'DNS',
    description: 'Domain Name System translates domain names to IP addresses, allowing users to access websites with human-readable names.',
  },
  {
    term: 'VPN',
    description: 'Virtual Private Network extends a private network across a public network, enabling users to send and receive data securely.',
  },
  {
    term: 'Firewall',
    description: 'A network security device that monitors and filters incoming and outgoing network traffic based on an organization\'s previously established security policies.',
  },
  {
    term: 'IDS/IPS',
    description: 'Intrusion Detection Systems / Intrusion Prevention Systems monitor network traffic for suspicious activity and prevent attacks.',
  },
  {
    term: 'SIEM',
    description: 'Security Information and Event Management provides real-time analysis of security alerts generated by network hardware and applications.',
  },
  {
    term: 'SSL/TLS',
    description: 'Protocols for securing communications over a computer network.',
  },
  {
    term: 'Encryption',
    description: 'The process of encoding data to prevent unauthorized access.',
  },
  {
    term: 'VPN Tunneling',
    description: 'A method of sending encrypted data over a network.',
  },
  {
    term: 'Port Scanning',
    description: 'The act of systematically scanning a computer\'s ports to find vulnerabilities.',
  },
  {
    term: 'VLAN',
    description: 'Virtual Local Area Network divides a network into multiple virtual networks for security and organization.',
  },
  {
    term: 'NAT',
    description: 'Network Address Translation allows a network to use one set of IP addresses for internal traffic and another for external traffic.',
  },
  {
    term: 'Proxy Server',
    description: 'Acts as an intermediary for requests from clients seeking resources from other servers.',
  },
  {
    term: 'Packet Sniffing',
    description: 'The practice of monitoring and capturing all data packets passing through a given network.',
  },
  {
    term: 'DDoS Protection',
    description: 'Measures to protect a network or server from Distributed Denial-of-Service attacks.',
  },
  {
    term: 'Bandwidth',
    description: 'The maximum rate of data transfer across a given path.',
  },
  {
    term: 'Latency',
    description: 'The delay before a transfer of data begins following an instruction for its transfer.',
  },
  {
    term: 'Load Balancer',
    description: 'A device that distributes network or application traffic across multiple servers to improve responsiveness and availability.',
  },
  {
    term: 'Content Filter',
    description: 'Software that screens and restricts the content delivered over the web to a user.',
  },
  {
    term: 'SSL Inspection',
    description: 'The process of decrypting SSL/TLS encrypted traffic to inspect its content for security threats.',
  },
  {
    term: 'ACL (Access Control List)',
    description: 'A set of rules that controls the incoming and outgoing network traffic on a device or network, based on a set of criteria.',
  },
  {
    term: 'ARP (Address Resolution Protocol)',
    description: 'A protocol used to map an IP address to a physical machine address (MAC address) on a local area network.',
  },
  {
    term: 'BGP (Border Gateway Protocol)',
    description: 'The protocol underlying the global routing system of the internet, managing how packets get routed from network to network through the exchange of routing and reachability information among edge routers.',
  },
  {
    term: 'Botnet',
    description: 'A network of private computers infected with malicious software and controlled as a group without the owners\' knowing, often to send spam or participate in DDoS attacks.',
  },
  {
    term: 'CIDR (Classless Inter-Domain Routing)',
    description: 'A method for allocating IP addresses and IP routing that is more flexible than older systems like Classful networking.',
  },
  {
    term: 'DDoS (Distributed Denial of Service)',
    description: 'An attack that attempts to disrupt the normal traffic of a targeted server, service, or network by overwhelming the target or its surrounding infrastructure with a flood of Internet traffic.',
  },
  {
    term: 'DHCP (Dynamic Host Configuration Protocol)',
    description: 'A network management protocol used on IP networks whereby a DHCP server dynamically assigns an IP address and other network configuration parameters to each device on a network.',
  },
  {
    term: 'DNS (Domain Name System)',
    description: 'The hierarchical and decentralized naming system used to identify computers, services, and other resources reachable through the internet or other IP networks by translating human-friendly domain names to machine-readable IP addresses.',
  },
  {
    term: 'DPI (Deep Packet Inspection)',
    description: 'A form of computer network packet filtering that examines the data part (and possibly also the header) of a packet as it passes an inspection point, searching for non-compliance with or violations of protocol, viruses, spam, intrusions, or defined criteria.',
  },
  {
    term: 'EDR (Endpoint Detection and Response)',
    description: 'A cybersecurity technology that addresses the need for continuous monitoring and response to advanced threats, specifically focusing on endpoint devices.',
  },
  {
    term: 'Firewall',
    description: 'A network security system that monitors and controls incoming and outgoing network traffic based on predetermined security rules.',
  },
  {
    term: 'Honeypot',
    description: 'A security mechanism set to detect, deflect, or, in some manner, counteract attempts at unauthorized use of information systems, essentially a trap to catch cyber attackers.',
  },
  {
    term: 'IDS (Intrusion Detection System)',
    description: 'A device or software application that monitors a network or systems for malicious activity or policy violations.',
  },
  {
    term: 'IPS (Intrusion Prevention System)',
    description: 'An extension of IDS that not only detects but also prevents identified threats.',
  },
  {
    term: 'IPv4/IPv6',
    description: 'Internet Protocol version 4 and version 6 are the fourth and sixth versions of the Internet Protocol, respectively, used to identify devices on a network through an addressing system.',
  },
  {
    term: 'MAC Address (Media Access Control Address)',
    description: 'A unique identifier assigned to a network interface controller (NIC) for use as a network address in communications within a network segment.',
  },
  {
    term: 'Malware',
    description: 'Any software intentionally designed to cause damage to a computer, server, client, or computer network.',
  },
  {
    term: 'NAT (Network Address Translation)',
    description: 'A method of remapping one IP address space into another by modifying network address information in the IP header of packets while they are in transit across a traffic routing device.',
  },
  {
    term: 'NIDS (Network Intrusion Detection System)',
    description: 'A system that analyzes incoming network traffic to identify any suspicious patterns that may indicate a network or system attack.',
  },
  {
    term: 'NIPS (Network Intrusion Prevention System)',
    description: 'A system that not only detects but also prevents network attacks by blocking detected malicious traffic.',
  },
  {
    term: 'OSI Model (Open Systems Interconnection Model)',
    description: 'A conceptual framework used to understand network interactions in seven layers: physical, data link, network, transport, session, presentation, and application.',
  },
  {
    term: 'Packet Sniffing',
    description: 'The practice of monitoring and capturing all data packets passing through a given network using a software application or hardware device.',
  },
  {
    term: 'Phishing',
    description: 'A cyber attack employing deceptive communications, typically email, aimed at tricking individuals into revealing personal information, installing malware, or opening links to infected websites.',
  },
  {
    term: 'Ransomware',
    description: 'A type of malicious software designed to block access to a computer system or data, typically by encrypting it, until a sum of money is paid.',
  },
  {
    term: 'SIEM (Security Information and Event Management)',
    description: 'A set of integrated tools designed to provide a comprehensive and real-time view of the security posture of an organization by collecting, analyzing, and presenting security data from various sources.',
  },
  {
    term: 'SSL/TLS (Secure Sockets Layer / Transport Layer Security)',
    description: 'Cryptographic protocols designed to provide communications security over a computer network, widely used for web browsers and other applications that require data to be securely exchanged.',
  },
  {
    term: 'Subnet',
    description: 'A logical subdivision of an IP network, breaking down a large network into smaller, manageable pieces.',
  },
  {
    term: 'TCP/IP (Transmission Control Protocol/Internet Protocol)',
    description: 'The basic communication language or set of protocols for the Internet.',
  },
  {
    term: 'Threat Intelligence',
    description: 'Evidence-based knowledge, including context, mechanisms, indicators, implications, and actionable advice, about an existing or emerging menace or hazard to assets that can be used to inform decisions regarding the subject\'s response to that menace or hazard.',
  },
  {
    term: 'VLAN (Virtual Local Area Network)',
    description: 'A method to create independent networks within a physical network, improving the management and security of data traffic.',
  },
  {
    term: 'VPN (Virtual Private Network)',
    description: 'A service that encrypts your internet traffic and protects your online identity by hiding your IP address, making your internet activity more secure.',
  },
  {
    term: 'WAF (Web Application Firewall)',
    description: 'A specific form of application firewall that filters, monitors, and blocks HTTP traffic to and from a web service.',
  },
  {
    term: 'XSS (Cross-Site Scripting)',
    description: 'A security vulnerability typically found in web applications, allowing attackers to inject malicious scripts into content from otherwise trusted websites.',
  },
  {
    term: 'Zero Day',
    description: 'A vulnerability in software, hardware, or firmware that is unknown to the party or parties responsible for patching or otherwise fixing the vulnerability.',
  },
  {
    term: 'MITM (Man In The Middle Attack)',
    description: 'An attack where the attacker secretly intercepts and alters the communication between two parties who believe they are directly communicating with each other.',
  },
  {
    term: 'SOC (Security Operations Center)',
    description: 'A centralized unit that deals with security issues on an organizational and technical level, focusing on real-time monitoring, detection, analysis, and response to cybersecurity incidents.',
  },
  {
    term: 'Encryption',
    description: 'The process of converting information or data into a code to prevent unauthorized access.',
  },
  {
    term: 'Threat Hunting',
    description: 'The proactive search for malicious actors or activities that are hidden within a network and might not be detected by traditional security tools.',
  },
  {
    term: 'Vulnerability',
    description: 'A weakness which can be exploited by a threat actor, such as an attacker, to perform unauthorized actions within a computer system.',
  },
  {
    term: 'Penetration Testing',
    description: 'The practice of testing a computer system, network, or web application to find vulnerabilities that an attacker could exploit.',
  },
  {
    term: 'Social Engineering',
    description: 'The use of deception to manipulate individuals into divulging confidential or personal information that may be used for fraudulent purposes.',
  },
  {
    term: '2FA (Two-Factor Authentication)',
    description: 'A security process in which users provide two different authentication factors to verify themselves, enhancing the security of their account and the network.',
  },
  {
    term: 'Incident Response',
    description: 'The organized approach to addressing and managing the aftermath of a security breach or cyber attack, aiming to limit damage and reduce recovery time and costs.',
  },
  {
    term: 'Patch Management',
    description: 'The process of distributing and applying updates to software, including security patches, to protect against vulnerabilities exploited by hackers.',
  },
  {
    term: 'Rootkit',
    description: 'A collection of malicious software tools that enable unauthorized access to a computer or area of its software and often hide the existence of certain processes or programs.',
  },
  {
    term: 'Sandboxing',
    description: 'A security technique for separating running programs, usually in an effort to mitigate system failures or software vulnerabilities from spreading.',
  },
];